services:
  db:
    image: postgres:latest
    restart: always
    container_name: todo-db
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./todo-db_data:/var/lib/postgresql/data
