spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tododb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    locations: classpath:/db/migration

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /api-docs/swagger-ui.html

